kind: Job
apiVersion: batch/v1
metadata:
 name: mulux-prueba
 namespace: esgomezm-namespace
spec:
  parallelism: 1
  completions: 1
  backoffLimit: 10
  template:
   metadata:
    labels:
      job-name: mulux-prueba
   spec:
     volumes:
       - name: data
         hostPath:
           path: /srv/bcss/egomez/3dprotucell_data/
           type: Directory
     containers:
       - name: nombre-contenedor
         image: '163.117.178.17:5000/mu_lux_cz_egomez_tf2.1gpu'
         command:
           - python
         args:
           - MU_Lux_CZ/prueba.py
         workingDir: /data
         resources:
          limits:
           cpu: '4'
           memory: 14Gi
           nvidia.com/gpu: 1
         volumeMounts:
           - name: data
             mountPath: /data
         terminationMessagePath: /data/termination-log
         terminationMessagePolicy: File
         imagePullPolicy: Always
     restartPolicy: OnFailure
     priorityClassName: low
