kind: Job
apiVersion: batch/v1
metadata:
 name: mulux-multiout-v01
 namespace: esgomezm-namespace
 labels:
   job-name: esgomezm-mulux-multiout-v01
spec:
 backoffLimit: 1
 template:
   metadata:
     creationTimestamp: null
   spec:
     volumes:
       - name: data
         hostPath:
           path: /srv/bcss/egomez/3dprotucell_data/ 
           type: Directory
     containers:
       - name: nombre-contenedor
         image: '163.117.178.17:5000/mu_lux_cz_egomez_tf2.1gpu'
         command:
           - python
         args:
           - MU_Lux_CZ/train.py
           - 'train_config/experiment_externaldata/config_multiout_external_data_001.json'
         workingDir: /data
         resources:
           requests:
            cpu: "4"
            memory: "14000"
           limits:
             nvidia.com/gpu: '1'
         volumeMounts:
           - name: data
             mountPath: /data
         terminationMessagePath: /dev/termination-log
         terminationMessagePolicy: File
         imagePullPolicy: Always
     nodeSelector:
         kubernetes.io/hostname: arges-biig
     restartPolicy: OnFailure
     terminationGracePeriodSeconds: 3000
     ttlSecondsAfterFinished: 2000
     backoffLimit: 1 #13
     priorityClassName: low

